_wandb:
    value:
        cli_version: 0.30.0
        e:
            9nbijgdtc9vcn00dp0xtbvdbsn4594tn:
                codePath: /home/bryzcoll/Escritorio/9no/Ciencia de Datos/MLOps/mlops-wine-quality/notebooks/wine_quality_mlops.ipynb
                codePathLocal: wine_quality_mlops.ipynb
                email: bryzcoll@gmail.com
                executable: /home/bryzcoll/Escritorio/9no/Ciencia de Datos/MLOps/mlops-wine-quality/.venv/bin/python
                git:
                    commit: fc240d481b68ae8ce7066379f64add106e4c48c1
                    remote: https://github.com/bryzcoll/mlops-wine-quality.git
                host: bryzcoll-OMEN-by-HP
                os: Linux-7.0.0-34-generic-x86_64-with-glibc2.39
                program: /home/bryzcoll/Escritorio/9no/Ciencia de Datos/MLOps/mlops-wine-quality/notebooks/wine_quality_mlops.ipynb
                python: CPython 3.13.2
                root: /home/bryzcoll/Escritorio/9no/Ciencia de Datos/MLOps/mlops-wine-quality/notebooks
                startedAt: "2026-10-05T02:41:35.710587Z"
                writerId: 9nbijgdtc9vcn00dp0xtbvdbsn4594tn
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.2
            "5": 0.30.0
            "8":
                - 1
            "12": 0.30.0
            "13": linux-x86_64
max_depth:
    value: 5
min_samples_leaf:
    value: 1
min_samples_split:
    value: 2
n_estimators:
    value: 50
random_state:
    value: 42
